apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-react-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-react-frontend
  template:
    metadata:
      labels:
        app: go-react-frontend
    spec:
      containers:
      - name: go-react-frontend
        image: go-react-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-react-frontend-service
spec:
  selector:
    app: go-react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort